version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash run.sh
    image: null-jobs-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/workspace
    depends_on:
      - db
    env_file:
      - .env

  bootstrap:
    build:
        context: .
        dockerfile: Dockerfile
    image: null-jobs-backend
    depends_on:
      - db
      - app
    volumes:
      - .:/workspace
    command: bash -c "python manage.py loaddata utils/seed/company.json && python manage.py loaddata utils/seed/job.json && python manage.py loaddata utils/seed/userprofile.json"
    env_file:
      - .env

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: null_jobs_backend_db
      MYSQL_USER: null_jobs_backend_user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
